"""Data model shared by sources, LLM stages and rendering."""
from __future__ import annotations

import hashlib
from dataclasses import asdict, dataclass, field
from datetime import date, datetime
from typing import Any


def make_id(*parts: str) -> str:
    """Stable short id for an item, derived from its identifying parts."""
    h = hashlib.sha1("\x1f".join(parts).encode()).hexdigest()
    return h[:12]


@dataclass
class Item:
    id: str
    source: str
    url: str
    published: datetime | None          # exact timestamp when the source has one
    day: date                           # local (or source-labelled) date shown in the report
    title: str | None = None            # None for release notes -> generated by the model
    kind: str | None = None             # release-note type (Feature, Changed...) or reading-list tag (blog...)
    content: str = ""                   # text handed to the model
    content_origin: str = "feed"        # article | feed | curator_note | release_note
    extra: dict[str, Any] = field(default_factory=dict)

    # Filled by LLM stages
    depth: str | None = None            # announcement | release_note | how_to | deep_technical | research | ...
    full_text_adds: str | None = None   # what the full piece offers beyond the summary
    stars: int | None = None            # 1-5 from the final review; 4-5 <=> verdict "read"
    summary: str | None = None
    gen_title: str | None = None
    relevant: bool = True               # Dev Blog AI/Cloud filter
    prescreen: str | None = None        # "skip" | "candidate"
    verdict: str | None = None          # "read" | "skip"
    reason: str | None = None
    llm_error: str | None = None

    @property
    def word_count(self) -> int:
        return len(self.content.split())

    @property
    def truncated(self) -> bool:
        return self.content.rstrip().endswith("[…truncated]")

    @property
    def display_title(self) -> str:
        return self.title or self.gen_title or "(untitled)"

    def to_dict(self) -> dict:
        d = asdict(self)
        d["published"] = self.published.isoformat() if self.published else None
        d["day"] = self.day.isoformat()
        return d

    @classmethod
    def from_dict(cls, d: dict) -> "Item":
        d = {k: v for k, v in d.items() if k in cls.__dataclass_fields__}
        d["published"] = datetime.fromisoformat(d["published"]) if d.get("published") else None
        d["day"] = date.fromisoformat(d["day"])
        return cls(**d)


@dataclass
class SourceStats:
    status: str = "ok"                  # ok | empty | partial (some pages unreadable) | http_error | parse_error
    http_status: int | None = None
    items_in_feed: int = 0
    oldest_item_in_feed: str | None = None
    newest_item_in_feed: str | None = None
    found_in_window: int = 0
    new_after_dedup: int = 0
    kept: int = 0
    read_fully: int = 0
    latest_item_date: str | None = None
    latest_item_title: str | None = None
    error: str | None = None
    note: str | None = None             # e.g. "feed only reaches back to ..."


@dataclass
class SourceResult:
    key: str
    items: list[Item] = field(default_factory=list)
    stats: SourceStats = field(default_factory=SourceStats)
